### PR TITLE
new language SK

### PR DESCRIPTION
**Pull request by lukasprelovsky**
new language SK

### CODE REVIEW

**Comment by lukasprelovsky** [comment]
I can not upload it to GitHub
Download here
https://drive.google.com/file/d/0BzYFPI0jil9vZ2hiN2oyVG1FRU0/view?usp=sharing

**Comment by hlashbrooke** [comment]
Thanks for this - I will include it in the next release of the plugin :)

**Comment by lukasprelovsky** [comment]
Can you delete it from Google Drive? 
when released the update?

**Comment by hlashbrooke** [comment]
I'm closing this PR as translations can now be added using the WP translation UI: https://translate.wordpress.org/projects/wp-plugins/woocommerce-email-validation

**Pull request closed without merging**
